---

 - name: Adding user list
   hosts: managed_nodes
  
   tasks:
   - name: Add users
     no_log: true
     with_items: "{{ users }}"
     user:
       name: "{{item.key}}"
       password: "{{ item.value | password_hash ('sha512')}}"
       state: present
       update_password: on_create