---

- name: Uptime report
  serveruptime: ~
  register: result

- name: Generate report
  delegate_to: localhost
  vars: 
    server_uptime: "{{ result.uptime }}"
  template:
      src: "uptime_report_tmpl.j2"
      dest: "{{playbook_dir}}/reports/{{ inventory_hostname }}"